# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devtui < Formula
  desc "A Swiss Army knife for developers"
  homepage "https://devtui.com"
  version "0.12.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skatkov/homebrew-tap/releases/download/devtui-v0.12.0/devtui_Darwin_x86_64.tar.gz"
      sha256 "e531f7cce89e26db66f03ca6e8ed2786c2ba2803925164368c5f99cc8e498ac3"

      def install
        bin.install "devtui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skatkov/homebrew-tap/releases/download/devtui-v0.12.0/devtui_Darwin_arm64.tar.gz"
      sha256 "f77ef76304e07d88140c704aa3d2b616ec0bb3366553e5a74cc5e8186e04ca15"

      def install
        bin.install "devtui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/skatkov/homebrew-tap/releases/download/devtui-v0.12.0/devtui_Linux_x86_64.tar.gz"
        sha256 "58c146522c00f78f376bbbb152286352d2d11b53a09cd303bec9bc03212b91db"

        def install
          bin.install "devtui"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/skatkov/homebrew-tap/releases/download/devtui-v0.12.0/devtui_Linux_arm64.tar.gz"
        sha256 "0127ddd3394e12b60c122f405ae392d13e13a5f9a872cb564414971ca6512b85"

        def install
          bin.install "devtui"
        end
      end
    end
  end
end
