# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Poshtui < Formula
  desc "Glamorous API documentation browser in console for Ruby developers"
  homepage "https://poshtui.com"
  version "0.7.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skatkov/homebrew-tap/releases/download/0.7.4/homebrew-tap_Darwin_x86_64.tar.gz"
      sha256 "5d385b2966fdc09196bd0565109a88548889272bf420be087564bbd609f98832"

      def install
        bin.install "posh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skatkov/homebrew-tap/releases/download/0.7.4/homebrew-tap_Darwin_arm64.tar.gz"
      sha256 "ae843ce5e72e56c6081d0af2f568ff2669a448f11cd5a879a4aa66f235f60102"

      def install
        bin.install "posh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/skatkov/homebrew-tap/releases/download/0.7.4/homebrew-tap_Linux_x86_64.tar.gz"
      sha256 "a943cf77e3489db4b10788e7df33217c1053d417fabbf144ba11bd1defff99ff"

      def install
        bin.install "posh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skatkov/homebrew-tap/releases/download/0.7.4/homebrew-tap_Linux_arm64.tar.gz"
      sha256 "922d6006a02842665ff15ba69445b3611953793c4716a1f378500d4b336c8b4b"

      def install
        bin.install "posh"
      end
    end
  end

  def post_install
    ohai "'posh' needs documentation to be stored in ~/Library/Application Support/posh folder"
    ohai "Please, run `posh docsets` manually to download documentation"
  end
end
