# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Poshtui < Formula
  desc "Glamorous API documentation browser in console for Ruby developers"
  homepage "https://poshtui.com"
  version "0.11.1"

  on_macos do
    on_intel do
      url "https://github.com/skatkov/homebrew-tap/releases/download/0.11.1/homebrew-tap_Darwin_x86_64.tar.gz"
      sha256 "c86d227943f26c68e0ae77e14d54c9bf64c7169dd942dc1f086db21dcedf6972"

      def install
        bin.install "posh"
      end
    end
    on_arm do
      url "https://github.com/skatkov/homebrew-tap/releases/download/0.11.1/homebrew-tap_Darwin_arm64.tar.gz"
      sha256 "45b717389f9294c95f9efa6ca9a48d592a6989bd0863b0d9f649f97e8baa2a7a"

      def install
        bin.install "posh"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/skatkov/homebrew-tap/releases/download/0.11.1/homebrew-tap_Linux_x86_64.tar.gz"
        sha256 "b81089427c1f8ffac7ae63e8a10511f10d29d13f8ef4ecc718a5d16ab2214b1d"

        def install
          bin.install "posh"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/skatkov/homebrew-tap/releases/download/0.11.1/homebrew-tap_Linux_arm64.tar.gz"
        sha256 "a6ba2699ca3b9978d69b5ba3e57f9e64263c492d96e4ad8703c935e9c657f76f"

        def install
          bin.install "posh"
        end
      end
    end
  end

  def post_install
    ohai "'posh' needs documentation to be stored in ~/Library/Application Support/posh folder"
    ohai "Please, run `posh docsets` manually to download documentation"
  end
end
