# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Poshtui < Formula
  desc "Terminal based documentation browser for developers"
  homepage "https://poshtui.com"
  version "0.28.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skatkov/homebrew-tap/releases/download/0.28.1/homebrew-tap_Darwin_x86_64.tar.gz"
      sha256 "57f0d2bb957be0315349d4897078e67c73ce9d7c79ca83fc9b15e08531ee1283"

      define_method(:install) do
        bin.install "posh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skatkov/homebrew-tap/releases/download/0.28.1/homebrew-tap_Darwin_arm64.tar.gz"
      sha256 "02f1a8440a513be9ca8660979fe9d3474bf86bae9f75406bb4b5952e05a8100f"

      define_method(:install) do
        bin.install "posh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skatkov/homebrew-tap/releases/download/0.28.1/homebrew-tap_Linux_x86_64.tar.gz"
      sha256 "9e48650eec404df1e601e48bdc8dea9ce2a6e51ff8b9ca025ef19e732cdbd1b0"
      define_method(:install) do
        bin.install "posh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skatkov/homebrew-tap/releases/download/0.28.1/homebrew-tap_Linux_arm64.tar.gz"
      sha256 "f170dc653b47a72c3ca88a14e6b63ac52f5bb917af95eb689b651403d1f6984c"
      define_method(:install) do
        bin.install "posh"
      end
    end
  end

  def post_install
    ohai "All done! Now run `posh sync` in a folder with your ruby project"
  end
end
