# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sepa < Formula
  desc "A Terminal User Interface (TUI) application for viewing and analyzing SEPA XML payment files"
  homepage "https://github.com/skatkov/sepatui"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skatkov/sepatui/releases/download/v0.1.2/sepatui_0.1.2_darwin_amd64.tar.gz"
      sha256 "31bac8503a5d1a2020b1bc26e656a48fcdf63257d2277b9e9f3a984bab2187c3"

      def install
        bin.install "sepatui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skatkov/sepatui/releases/download/v0.1.2/sepatui_0.1.2_darwin_arm64.tar.gz"
      sha256 "1a40ee8a942d378b261a1ab064c134446d1285dd4d9d8f3ece5c910b56eaa57f"

      def install
        bin.install "sepatui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/skatkov/sepatui/releases/download/v0.1.2/sepatui_0.1.2_linux_amd64.tar.gz"
      sha256 "1cf43de1d721032362361582ce3e50dc3812cb39249b47e7bcadb8fa36067e25"
      def install
        bin.install "sepatui"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/skatkov/sepatui/releases/download/v0.1.2/sepatui_0.1.2_linux_armv6.tar.gz"
      sha256 "7124f8d04353fbdbcfee8e497e0edbd015abca606f4052d32b7adda1fe30941a"
      def install
        bin.install "sepatui"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/skatkov/sepatui/releases/download/v0.1.2/sepatui_0.1.2_linux_arm64.tar.gz"
      sha256 "90798d5104728ee08f3631d1f9c30f8119fa2aa587d58fec112bbb5dec99cf83"
      def install
        bin.install "sepatui"
      end
    end
  end
end
