# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sepa < Formula
  desc "A Terminal User Interface (TUI) application for viewing and analyzing SEPA XML payment files"
  homepage "https://github.com/skatkov/sepatui"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skatkov/sepatui/releases/download/v0.2.0/sepatui_0.2.0_darwin_amd64.tar.gz"
      sha256 "ee92a84f5f0b95faa99297c2330875cce5c269f5b7416be6c3da6363c0872a9f"

      def install
        bin.install "sepatui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skatkov/sepatui/releases/download/v0.2.0/sepatui_0.2.0_darwin_arm64.tar.gz"
      sha256 "360a1e19547cff37b59b53a250507c042063fccba59c3b197070a5f3059264ce"

      def install
        bin.install "sepatui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/skatkov/sepatui/releases/download/v0.2.0/sepatui_0.2.0_linux_amd64.tar.gz"
      sha256 "40a19bc2aebbeef610610de9a72bfd870399790f79ec871a781577d1584fb008"
      def install
        bin.install "sepatui"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/skatkov/sepatui/releases/download/v0.2.0/sepatui_0.2.0_linux_arm64.tar.gz"
      sha256 "90436e76190806ff9675b120582b29bf25d44b2d725ce093fb21c885e3217046"
      def install
        bin.install "sepatui"
      end
    end
  end
end
