# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stoic < Formula
  desc "Command-line application for daily journaling with plain-text files"
  homepage "https://github.com/skatkov/stoic"
  version "0.6.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skatkov/stoic/releases/download/0.6.2/stoic_Darwin_x86_64.tar.gz"
      sha256 "3e747fc96bb0faed8514ce9d3a9bc6931186ec9f9449343a5d86323a214cd866"

      def install
        bin.install "stoic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skatkov/stoic/releases/download/0.6.2/stoic_Darwin_arm64.tar.gz"
      sha256 "f7f77706508ec7e09b631ec5888b420fd27c85fcf99642df447782a1e208d39b"

      def install
        bin.install "stoic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skatkov/stoic/releases/download/0.6.2/stoic_Linux_arm64.tar.gz"
      sha256 "7abeca398aa99264e4c37c255d5f8824712f65444b3d6b44784294a9d1286fba"

      def install
        bin.install "stoic"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/skatkov/stoic/releases/download/0.6.2/stoic_Linux_x86_64.tar.gz"
      sha256 "ee39cafb761a24cf01a136b23a8583ec1c3e3f45d3c1c67dff5849009d041022"

      def install
        bin.install "stoic"
      end
    end
  end
end
