# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stoic < Formula
  desc "Command-line application for daily journaling with plain-text files"
  homepage "https://github.com/skatkov/stoic"
  version "0.6.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/skatkov/stoic/releases/download/0.6.1/stoic_Darwin_arm64.tar.gz"
      sha256 "52178b46a4581af71d9b63fedb13894c5c933007b20f701d67f3223f7bae6993"

      def install
        bin.install "stoic"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/skatkov/stoic/releases/download/0.6.1/stoic_Darwin_x86_64.tar.gz"
      sha256 "c7f0d0a5c8431bd1f233a41001f68449441c63b65168be18cd5b7818c9650025"

      def install
        bin.install "stoic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skatkov/stoic/releases/download/0.6.1/stoic_Linux_arm64.tar.gz"
      sha256 "da61f9b12b89ba34f5b1e401a5b3aaa2cbd9a2c6b4d808b74fe8a0e432cacf5c"

      def install
        bin.install "stoic"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/skatkov/stoic/releases/download/0.6.1/stoic_Linux_x86_64.tar.gz"
      sha256 "d86bada99b4b243e1d83562d25ca68f65b96d87e990e937d9b65b80e80ad8c38"

      def install
        bin.install "stoic"
      end
    end
  end
end
