# This file was generated by GoReleaser. DO NOT EDIT.
cask "devtui" do
  name "devtui"
  desc "A Swiss Army knife for developers"
  homepage ""
  version "0.30.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devtui"

  on_macos do
    on_intel do
      url "https://github.com/skatkov/devtui/releases/download/v#{version}/devtui_Darwin_x86_64.tar.gz"
      sha256 "0c2ed907e827963e4ad05cd6ab3894a9456bdabeac9dd69d723ddc423f7209f8"
    end
    on_arm do
      url "https://github.com/skatkov/devtui/releases/download/v#{version}/devtui_Darwin_arm64.tar.gz"
      sha256 "b9ae4ac4e74cb7465e18173b75609b96f0cc7ae056b68d64da6a1c3bc72b9d16"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/skatkov/devtui/releases/download/v#{version}/devtui_Linux_x86_64.tar.gz"
      sha256 "0f6c69dc453e5f3d87622a76b44bc67b911e1e5fbf41dccfaa0fdd93c2c338b0"
    end
    on_arm do
      url "https://github.com/skatkov/devtui/releases/download/v#{version}/devtui_Linux_arm64.tar.gz"
      sha256 "6dc0fdb81e5a148d2f44131eb62bdd3dec9530ea42fb2bd5b8211251416a5d67"
    end
  end

  # No zap stanza required
end
