# This file was generated by GoReleaser. DO NOT EDIT.
cask "devtui" do
  name "devtui"
  desc "A Swiss Army knife for developers"
  homepage ""
  version "0.32.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devtui"

  on_macos do
    on_intel do
      url "https://github.com/skatkov/devtui/releases/download/v#{version}/devtui_Darwin_x86_64.tar.gz"
      sha256 "986ccaab42d1fef177bc6ea7e21ed64a902ecc77f33913b1a93f458cc492f151"
    end
    on_arm do
      url "https://github.com/skatkov/devtui/releases/download/v#{version}/devtui_Darwin_arm64.tar.gz"
      sha256 "6265a73e50b517d4944d5eeb18b9817fed0ce4a4de4aaf897812fbea868965d6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/skatkov/devtui/releases/download/v#{version}/devtui_Linux_x86_64.tar.gz"
      sha256 "467d87f286d8b7f7575b67e7042391197af0a20b71167d2780ae92c763cc4bdc"
    end
    on_arm do
      url "https://github.com/skatkov/devtui/releases/download/v#{version}/devtui_Linux_arm64.tar.gz"
      sha256 "3460cde193895dfac2b8f532d77d71e60080e8e380ab63dabd146c71f77831c6"
    end
  end

  caveats do
    "Linux user need to install additional dependencies."
    ""
    "• Wayland: brew install wl-clipboard"
    "• X11: brew install xclip (or xsel)"
    ""
    "To check your session type: echo $XDG_SESSION_TYPE"
  end

  # No zap stanza required
end
