# This file was generated by GoReleaser. DO NOT EDIT.
cask "poshtui" do
  version "0.27.1"

  on_macos do
    on_intel do
      sha256 "189848b7207b93a8193fa4e8076cf2fbf7fd8bd56c8d0bdfa0d5ea4b45654fd0"
      url "https://github.com/skatkov/homebrew-tap/releases/download/#{version}/homebrew-tap_Darwin_x86_64.tar.gz",
        verified: "github.com/skatkov/homebrew-tap"
    end
    on_arm do
      sha256 "5a78f589eb1763a66f81960e2294cfd7341364d407e620dbf92f6c2c2a24be4b"
      url "https://github.com/skatkov/homebrew-tap/releases/download/#{version}/homebrew-tap_Darwin_arm64.tar.gz",
        verified: "github.com/skatkov/homebrew-tap"
    end
  end

  on_linux do
    on_intel do
      sha256 "d583fc58fd7b50a37b00db0fb62ae0371a996ea58d3b2f36e0791a7f518c8cd9"
      url "https://github.com/skatkov/homebrew-tap/releases/download/#{version}/homebrew-tap_Linux_x86_64.tar.gz",
        verified: "github.com/skatkov/homebrew-tap"
    end
    on_arm do
      sha256 "698c17308893d4efb1b6fb701c5df4489b08c5444730785d27973df1621fa224"
      url "https://github.com/skatkov/homebrew-tap/releases/download/#{version}/homebrew-tap_Linux_arm64.tar.gz",
        verified: "github.com/skatkov/homebrew-tap"
    end
  end

  name "poshtui"
  desc "Terminal based documentation browser for Ruby developers"
  homepage "https://poshtui.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "posh"

  # No zap stanza required

  caveats <<~EOS
    All done! Now run `posh sync` in a folder with your ruby project.
  EOS
end
