# This file was generated by GoReleaser. DO NOT EDIT.
cask "poshtui" do
  version "0.30.2"

  on_macos do
    on_intel do
      sha256 "5b69326860e8fde67080d1cf2bdbcec44adbc25506f3c8329ff781eeacfd6389"
      url "https://github.com/skatkov/homebrew-tap/releases/download/#{version}/homebrew-tap_Darwin_x86_64.tar.gz",
        verified: "github.com/skatkov/homebrew-tap"
    end
    on_arm do
      sha256 "366ed738075f4624e16f734bd485d308909949650bc5dd1b92d6c1c7d404e6bb"
      url "https://github.com/skatkov/homebrew-tap/releases/download/#{version}/homebrew-tap_Darwin_arm64.tar.gz",
        verified: "github.com/skatkov/homebrew-tap"
    end
  end

  on_linux do
    on_intel do
      sha256 "63b37b32f268289e31150ba3b0ccf24500de299014790f469f4cdf0d5afb48c0"
      url "https://github.com/skatkov/homebrew-tap/releases/download/#{version}/homebrew-tap_Linux_x86_64.tar.gz",
        verified: "github.com/skatkov/homebrew-tap"
    end
    on_arm do
      sha256 "ba1c1fe4c4cf8efecb1ef26cf573c97ecf5c129209e47be9aa5d70b4dfc66762"
      url "https://github.com/skatkov/homebrew-tap/releases/download/#{version}/homebrew-tap_Linux_arm64.tar.gz",
        verified: "github.com/skatkov/homebrew-tap"
    end
  end

  name "poshtui"
  desc "Terminal based documentation browser for Ruby developers"
  homepage "https://poshtui.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "posh"

  # No zap stanza required

  caveats <<~EOS
    All done! Now run `posh sync` in a folder with your ruby project.
  EOS
end
