# This file was generated by GoReleaser. DO NOT EDIT.
cask "poshtui" do
  version "0.25.0"

  on_macos do
    on_intel do
      sha256 "5cad0701a36d0910ce0957b08fa4296c601618a84ab3fa5b66617b3e866e2dfc"
      url "https://github.com/skatkov/homebrew-tap/releases/download/#{version}/homebrew-tap_Darwin_x86_64.tar.gz",
        verified: "github.com/skatkov/homebrew-tap"
    end
    on_arm do
      sha256 "5e3dc3c9518970b5acebf6b2afe82c320bb69ec7b1ec4f4bd1b2d34db4589d63"
      url "https://github.com/skatkov/homebrew-tap/releases/download/#{version}/homebrew-tap_Darwin_arm64.tar.gz",
        verified: "github.com/skatkov/homebrew-tap"
    end
  end

  on_linux do
    on_intel do
      sha256 "5c1cd74b423544216aa201cf0b87c7e39da212d3c4ed6c889622ea10a115d37c"
      url "https://github.com/skatkov/homebrew-tap/releases/download/#{version}/homebrew-tap_Linux_x86_64.tar.gz",
        verified: "github.com/skatkov/homebrew-tap"
    end
    on_arm do
      sha256 "81c3e3547d2d3abcd17a436a762d96dfbff205b48f6c44726355c813a7453bdd"
      url "https://github.com/skatkov/homebrew-tap/releases/download/#{version}/homebrew-tap_Linux_arm64.tar.gz",
        verified: "github.com/skatkov/homebrew-tap"
    end
  end

  name "poshtui"
  desc "Terminal based documentation browser for Ruby developers"
  homepage "https://poshtui.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "posh"

  # No zap stanza required

  caveats <<~EOS
    All done! Now run `posh sync` in a folder with your ruby project.
  EOS
end
